contacts/urls.py
from django.urls import path, include
from . import views

app_name = 'contacts'

urlpatterns = [
    path('new', views.new_contact, name='new_contact'),
    path('<int:pk>', views.contact_details.as_view(), name='view_contact'),
    path('', views.ViewContacts, name='all_contacts'),
    path('update/<int:pk>', views.update_contact.as_view(), name='update_contact'),
    path('delete/<int:pk>', views.delete_contact.as_view(), name='delete_contact'),
    path('search', views.getActors, name='search'),
    path('filtered', views.filterContacts, name='filter'),
    path('bysex', views.filterBySex, name='filter_sex'),
    path('byjob', views.filterByJob, name='filter_job'),
    path('bynat', views.filterByNationality, name='filter_nationality')

]

meetings/urls.py
from django.urls import path, include
from . import views

app_name = 'meetings'

urlpatterns = [
    # path('new/<int:pk>', views.create_meeting, name='new_meeting-pk'),
    path('new', views.create_meeting, name='new_meeting'),
    # path('', views.all_meetings.as_view(), name='all_meetings'),
    path('', views.get_upcoming_meetings, name='all_meetings'),
    path('<int:pk>', views.meeting_details.as_view(), name='meeting_details'),
    path('delete/<int:pk>', views.delete_meeting.as_view(), name='delete_meeting')

]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'user'

urlpatterns = [
    path('home', views.homepage, name='home'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register_user, name='register'),
    path('profile', views.user_details, name='profile')
]

weconnect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contacts/', include('contacts.urls')),
    path('', include('django.contrib.auth.urls')), #Needed to use Django auth features (login, logout, etc.)
    path('', include('users.urls'))
]

meetings/models.py
from django.db import models
from django.contrib.auth.forms import User
from django.urls import reverse
from contacts.models import Contact

# Create your models here.

class Meeting(models.Model):
    date = models.DateField()
    time = models.TimeField()
    title = models.TextField(max_length=500)
    location = models.TextField(max_length=200)
    report = models.TextField(
        max_length=2000, 
        null=True
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True
    )
    contact = models.ForeignKey(
        Contact,
        on_delete=models.CASCADE,
        null=True
    )


    #REDIRECTS ON CONTACT CREATION
    def get_absolute_url(self):
        return reverse('meetings:meeting_details', kwargs={'pk': self.pk})

    #OVERRIDE SAVE METHOD to set default Meeting title if not provided
    def save(self, *args, **kwargs):
        if not self.title:
            self.title = "Meeting with {} {} on {}".format(self.contact.first_name, self.contact.last_name, 
            self.date) 
        super(Meeting, self).save(*args, **kwargs)
    

meetings/forms.py
from django import forms
from .models import Meeting


class MeetingForm(forms.ModelForm):
    
    class Meta:
        model = Meeting
        fields = ['date', 'time', 'title', 'location', 'contact']
        widgets = {
            'date': forms.DateInput(attrs={'type':'date'}),
            'time': forms.TimeInput(attrs={'type':'time'})
        }

meetings/views.py
import logging
from django.contrib.auth import get_user
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Meeting
from .forms import MeetingForm
from contacts.models import Contact


logger = logging.getLogger(__name__)

# Create your views here.

# GENERIC VIEWS
class new_meeting(generic.CreateView):
    """
    Description: 
    (Incomplete) Creates new meeting for request.user
    """

    model = Meeting
    fields = ['date', 'time', 'title', 'location', 'contact']
    template = ''

    # Overrides form_valid() to set contact.user to request.user
    def form_valid(self, form):
        form.instance.user = get_user(self.request)
        return super().form_valid(form)

class all_meetings(generic.ListView):
    """
    Description: 
    Lists all meetings of request.user
    """

    model = Meeting
    context_object_name = 'all_meetings'
    template_name = 'meetings/webpages/all_meetings.html'

class meeting_details(generic.DetailView):
    """
    Description: 
    Shows details of specified meeting
    """

    model = Meeting
    context_object_name = 'meeting'
    template_name = 'meetings/webpages/meeting_details.html'

class delete_meeting(generic.DeleteView):
    """
    Description: 
    Deletes meeting of request.user
    """

    model = Meeting
    template_name = 'meetings/forms/contact_confirm_delete.html'
    success_url = '/meetings/'


# CUSTOM VIEWS
def create_meeting(request):
    """
    Description: 
    Creates new meeting for the user

    Parameters:
    request
    """
    
    if request.method == 'POST':
        form = MeetingForm(request.POST)

        if form.is_valid:
            meeting = form.save(commit=False)
            # Set meeting user to request.user
            meeting.user = request.user
            meeting.save()
            return redirect(reverse('meetings:all_meetings'))
        else:
            return HttpResponse('<h4> MEETING CREATION FAILED </h4>')

    else:
        logger.error(request.user)
        form = MeetingForm()

        # Restrict contact choices to request.user contacts
        form.fields['contact'].queryset = Contact.objects.filter(user = request.user)

    template = 'meetings/forms/create_meeting.html'

    return render(request, template, {'form': form})

def get_upcoming_meetings(request):
    """
    Description: 
    Gets user's upcoming meetings
    """

    current_date = timezone.localdate()

    upcoming_meetings = Meeting.objects.filter(user = request.user, date__gte = current_date)

    context = {
        'all_meetings': upcoming_meetings
    }

    template = 'meetings/webpages/all_meetings.html'

    return render(request, template, context)

def get_past_meetings(request):
    """
    Description: 
    Gets user's previous meetings
    """

    current_date = timezone.localdate()

    upcoming_meetings = Meeting.objects.filter(user = request.user, date__lt = current_date)

    context = {
        'all_meetings': upcoming_meetings
    }

    template = 'meetings/webpages/all_meetings.html'

    return render(request, template, context)

meetings/templates/meetings/webpages/all_meetings.html
{% extends 'meetings/webpages/base.html' %}

{% block title %} Meetings {% endblock %}

{% block body %}

    <h2>UPCOMING MEETINGS</h2>
    {% if all_meetings %}
    <ul class="list-group list-group-flush">
        {% for meeting in all_meetings %}
        <li class="list-group-item">
            <a href="{% url 'meetings:meeting_details' meeting.id %}"> {{meeting.title}}, {{meeting.date}} </a>
        </li>
        {% endfor %}
    </ul>
    <br>
    {% else %}
    <br>
    <br>
    <p>No Meetings</p>
    <br>
    <br>
    {% endif %}
    <div class="container">
        <a href="{% url 'meetings:new_meeting' %}" class="btn btn-primary"> Setup Meeting </a>
    </div>

{% endblock %}

meetings/templates/meetings/webpages/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% if user.is_authenticated %}
        {% block title %}{% endblock %}
      {% else %}
        Must Log In
      {% endif%}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/modal.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">WeConnect</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          {% if user.is_authenticated %}
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'user:profile' %}">My Page</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contacts:all_contacts' %}">My Contacts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'meetings:all_meetings' %}">Meetings</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:logout' %}">Log Out</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search Contact Name" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        {% else %}
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:login' %}">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:register' %}">Sign Up</a>
            </li>
          </ul>
        {% endif %}
        </div>
      </div>
    </nav>
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        {% if user.is_authenticated %}
          {% block body %}
          {% endblock %}
        {% else %}
          <h4> Oops... You aren't logged in yet</h4>
        {% endif %}
    </div>
</body>
</html>

meetings/templates/meetings/webpages/meeting_details.html
{% extends 'meetings/webpages/base.html' %}

{% block title %} Meeting Details {% endblock %}

{% block body %}

  <ul class="list-group list-group-flush">
    <li class="list-group-item"> Title: {{meeting.title}} </li>
    <li class="list-group-item"> Date: {{meeting.date}} </li>
    <li class="list-group-item"> Time: {{meeting.time}} </li>
    <li class="list-group-item"> Location: {{meeting.location}} </li>
    <li class="list-group-item"> Contact: {{meeting.contact.first_name}} {{meeting.contact.last_name}} </li>
    {% comment %} <li class="list-group-item"> Known by: {{user}} </li> {% endcomment %}
  </ul>
  <br>
  <div class="container">
    <a href="{% url 'meetings:delete_meeting' meeting.id %}" class="btn btn-primary"> Delete Meeting </a>
    {% comment %} <a href="{% url 'contacts:update_contact' contact.id %}" class="btn btn-primary"> Update Contact </a> {% endcomment %}
  </div>

 
{% endblock %}