contacts/urls.py
from django.urls import path, include
from . import views

app_name = 'contacts'

urlpatterns = [
    path('new', views.new_contact, name='new_contact'),
    path('<int:pk>', views.contact_details.as_view(), name='view_contact'),
    path('', views.ViewContacts, name='all_contacts'),
    path('update/<int:pk>', views.update_contact.as_view(), name='update_contact'),
    path('delete/<int:pk>', views.delete_contact.as_view(), name='delete_contact'),
    path('search', views.getActors, name='search'),
    path('filtered', views.filterContacts, name='filter'),
    path('bysex', views.filterBySex, name='filter_sex'),
    path('byjob', views.filterByJob, name='filter_job'),
    path('bynat', views.filterByNationality, name='filter_nationality')

]

meetings/urls.py
from django.urls import path, include
from . import views

app_name = 'meetings'

urlpatterns = [
    # path('new/<int:pk>', views.create_meeting, name='new_meeting-pk'),
    path('new', views.create_meeting, name='new_meeting'),
    # path('', views.all_meetings.as_view(), name='all_meetings'),
    path('', views.get_upcoming_meetings, name='all_meetings'),
    path('<int:pk>', views.meeting_details.as_view(), name='meeting_details'),
    path('delete/<int:pk>', views.delete_meeting.as_view(), name='delete_meeting')

]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'user'

urlpatterns = [
    path('home', views.homepage, name='home'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register_user, name='register'),
    path('profile', views.user_details, name='profile')
]

weconnect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contacts/', include('contacts.urls')),
    path('', include('django.contrib.auth.urls')), #Needed to use Django auth features (login, logout, etc.)
    path('', include('users.urls'))
]

users/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import User
from django import forms


class UserRegistrationForm(UserCreationForm):
    # Additional fields for Django user class
    email = forms.EmailField()
    birthday = forms.DateField()
    sex = forms.CharField(max_length=1)
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    nationality = forms.CharField(max_length=100)


    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2', 'nationality', 'birthday', 'sex']
        widgets = {
            'birthday': forms.DateInput(attrs={'type':'date'})
        }

users/views.py
import logging
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login,logout
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from .forms import UserRegistrationForm


logger = logging.getLogger(__name__)

# Create your views here.
def homepage(request):
    """
    Description: 
    Renders homepage

    Parameters:
    request
    """

    logger.info("Redirecting to homepage")

    return render(request, "users/webpages/home.html")

def register_user(request):
    """
    Description: 
    Register new user. Redirects them to their profile page

    Parameters:
    request
    """
    
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)

        # If valid, save user details
        logger.info("CHECK:: Validating registration form data")
        if form.is_valid(): 
            logger.info("INFO:: Registration data valid.")
            new_user = form.save(commit=False)
            logger.info("INFO:: Setting email as username.")
            new_user.username = form.cleaned_data['email']
            new_user.set_password(form.cleaned_data['password2'])

            # If username is not the same as email ask for new input
            if new_user.username != form.cleaned_data['email']:
                form = UserRegistrationForm()
                # logger.warning("ISSUE:: Username must be the same as the email. Redirecting to registration page")
                # messages.info(request, "Username must be the same as the email.")
                return render(request, 'users/registration/register_user.html', {'form': form})

            new_user.save()
            logger.info("INFO:: Check successful. New user created and saved.")

            # Log in user and redirect to 'My Page'
            logger.info("INFO:: Attempting to log in New user.")
            email = form.cleaned_data['email']
            password = form.cleaned_data['password2']
            user = authenticate(request, username=email, password=password)
            
            if user is not None:
                login(request, user)
                logger.info("INFO:: New user logged in successfully. Redirecting to profile page")
                messages.success(request, "Registered successfully. Welcome.")
                return redirect(reverse('user:profile'))
            else:
                logger.error("ERROR:: User saved but authentication failed. Unable to log in.")
                return HttpResponse('<h1> ERROR AUTHENTICATING USER!!! </h1><br><p>Password: %s</p>' %password)    
        else:
            logger.error("ERROR:: Registration data invalid.")
    # Request for webpage
    else:
        form = UserRegistrationForm()

    logger.info("INFO:: Loading registration page.")
    return render(request, 'users/registration/register_user.html', {'form': form})

def login_user(request):
    """
    Description: 
    Validate login credentials and log-in user

    Parameters:
    request
    """

    if request.method == 'POST':
        email = request.POST["email"]
        password = request.POST["password"]

        logger.info("INFO:: Authenticating login details.")
        user = authenticate(request, username=email, password=password)

        if user is not None:
            logger.info("INFO:: Authentication successful. Attempting login.")
            login(request, user)
            logger.info("INFO:: Login successful. Redirecting to profile page.")
            # Redirect to a success page.
            return redirect(reverse('user:profile'))
        else:
            # Return an 'invalid login' error message.
            logger.error("ERROR: User authentication failed. Returning to login page.")
            messages.success(request, "User authentication failed. Check credentials.")
            return redirect(reverse('user:login'))

    else:
        logger.info("INFO:: Loading login page.")
        return render(request, "users/registration/login.html")

def user_details(request):
    """
    Description: 
    Renders current user's profile page

    Parameters:
    request
    """

    return render(request, "users/webpages/profile.html")

def logout_view(request):
    """
    Description: 
    Log out current user

    Parameters:
    request
    """
    logger.info("INFO:: Logging out user.")
    logout(request)
    # Redirect to a success page
    return redirect(reverse('user:home'))

users/templates/users/webpages/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">WeConnect</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          {% if user.is_authenticated %}
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'user:profile' %}">My Page</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contacts:all_contacts' %}">My Contacts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'meetings:all_meetings' %}">Meetings</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:logout' %}">Log Out</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        {% else %}
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:login' %}">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:register' %}">Sign Up</a>
            </li>
          </ul>
        {% endif %}
        </div>
      </div>
    </nav>
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}


        {% block body %}
        {% endblock %}
        
    </div>
</body>
</html>

users/templates/users/webpages/home.html
{% extends 'users/webpages/base.html' %}

{% block title %} Home {% endblock %}

{% block body %}
  <h1>Welcome.</h1>
  <a class="btn btn-primary" href=" {% url 'user:login' %} ">Log In</a>
{% endblock %}

users/templates/users/webpages/profile.html
{% extends 'users/webpages/base.html' %}

{% block title %}
  {% if user.is_authenticated %}
    My Page
  {% else %}
    Must Log In
  {% endif %}
{% endblock %}


{% block body %}

  {% if user.is_authenticated %}
    <div class="container">
      <div class="container text-center">
        {% comment %} <h4>Hello User N.o {{ user.id }}</h4> {% endcomment %}
        <h4>Hello {{ user.first_name }}</h4>
        <div class="row">
          <div class="col">
            Picture Here
          </div>
          <div class="col">
            <ul class="list-group list-group-flush">
              <li class="list-group-item"> Name: {{user.first_name}} {{user.last_name}} </li>
              <li class="list-group-item"> Nationality: {{user.nationality}} </li>
              <li class="list-group-item"> Email: {{user.email}} </li>
              <li class="list-group-item"> Job: {{user.job}} </li>
              <li class="list-group-item"> Experience (Years): {{user.experience}} </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  {% else %}
    <h4> Oops... You aren't logged in yet</h4>
  {% endif %}

  
{% endblock %}