contacts/urls.py
from django.urls import path, include
from . import views

app_name = 'contacts'

urlpatterns = [
    path('new', views.new_contact, name='new_contact'),
    path('<int:pk>', views.contact_details.as_view(), name='view_contact'),
    path('', views.ViewContacts, name='all_contacts'),
    path('update/<int:pk>', views.update_contact.as_view(), name='update_contact'),
    path('delete/<int:pk>', views.delete_contact.as_view(), name='delete_contact'),
    path('search', views.getActors, name='search'),
    path('filtered', views.filterContacts, name='filter'),
    path('bysex', views.filterBySex, name='filter_sex'),
    path('byjob', views.filterByJob, name='filter_job'),
    path('bynat', views.filterByNationality, name='filter_nationality')

]

meetings/urls.py
from django.urls import path, include
from . import views

app_name = 'meetings'

urlpatterns = [
    # path('new/<int:pk>', views.create_meeting, name='new_meeting-pk'),
    path('new', views.create_meeting, name='new_meeting'),
    # path('', views.all_meetings.as_view(), name='all_meetings'),
    path('', views.get_upcoming_meetings, name='all_meetings'),
    path('<int:pk>', views.meeting_details.as_view(), name='meeting_details'),
    path('delete/<int:pk>', views.delete_meeting.as_view(), name='delete_meeting')

]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'user'

urlpatterns = [
    path('home', views.homepage, name='home'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register_user, name='register'),
    path('profile', views.user_details, name='profile')
]

weconnect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contacts/', include('contacts.urls')),
    path('', include('django.contrib.auth.urls')), #Needed to use Django auth features (login, logout, etc.)
    path('', include('users.urls'))
]

contacts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.forms import User


# Create your models here.
class Contact(models.Model):
    first_name = models.TextField(max_length=200, default="")
    last_name = models.TextField(max_length=200, default="")

    #CHOICES for sex
    SEX_CHOICES = (
        ("M", "Male"),
        ("F", "Female")
    )
    sex = models.CharField(
        max_length=1,
        choices=SEX_CHOICES)

    nationality = models.TextField(max_length=200, default="")
    email = models.TextField(max_length=500, default="")
    job = models.TextField(max_length=200, default="")
    experience = models.IntegerField(default=0)
    birthday = models.DateField(null=True)
    bio = models.TextField(
        default='TBA',
        max_length=2000
    )
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE,
        null=True
    )

    #REDIRECTS ON CONTACT CREATION VIA CREATEVIEW
    def get_absolute_url(self):
        return reverse('contacts:view_contact', kwargs={'pk': self.pk})

    #STRING REPRESENTATION OF OBJECT (FOR ADMIN)
    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)

contacts/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    gender = forms.ChoiceField(
        choices=Contact.SEX_CHOICES
    )

    class Meta:
        model = Contact
        fields = ['first_name', 'last_name', 'gender', 'nationality', 'email', 'job', 'experience', 'birthday', 'bio']
        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }

contacts/views.py
import logging
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import generic
from .models import Contact
from .forms import ContactForm

# GENERIC VIEWS
class all_contacts(generic.ListView):
    """
    Description: 
    Shows contacts registered by current user (ListView)
    """

    model = Contact
    context_object_name = 'all_contacts'
    template_name = 'contacts/webpages/all_contacts.html'

class add_contact(LoginRequiredMixin, generic.CreateView):
    """
    Description: 
    Allows current user register new contact (CreateView)
    """
    
    model = Contact

    fields = ['first_name', 'last_name', 'sex', 'nationality',
              'email', 'job', 'experience', 'birthday', 'bio']
    
    # Overrides form_valid() to set contact.user to request.user
    def form_valid(self, form):
        form.instance.user = get_user(self.request)
        return super().form_valid(form)

    template_name = 'contacts/forms/create_contact.html'

class contact_details(generic.DetailView):
    """
    Description: 
    Shows details of contact registered by current user (DetailView)
    """

    model = Contact
    context_object_name = 'contact'
    template_name = 'contacts/webpages/contact_details.html'

class update_contact(generic.UpdateView):
    """
    Description: 
    Allows current user update details of a registered contact (UpdateView)
    """

    model = Contact
    fields = ['first_name', 'last_name', 'sex', 'nationality',
              'email', 'job', 'experience', 'birthday', 'bio']
    template_name = 'contacts/forms/update_contact.html'

class delete_contact(generic.DeleteView):
    """
    Description: 
    Allows current user delete a registered contact (DeleteView)
    """

    model = Contact
    template_name = 'contacts/forms/contact_confirm_delete.html'
    success_url = '/contacts/'


# CUSTOM VIEWS
def new_contact(request):
    """
    Description: 
    Registers new contact under current user

    Parameters:
    request
    """

    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            contact = form.save(commit=False)
            contact.user = get_user(request)
            contact.sex = form.cleaned_data['gender']
            contact.save()
            return redirect(reverse('contacts:all_contacts'))
        else:
            return HttpResponse('<h4> MEETING CREATION FAILED </h4>')

    else:
        form = ContactForm()

    return render(request, 'contacts/forms/create_contact.html', {'form': form})

def ViewContacts(request):
    """
    Description: 
    Shows contacts registered by current user

    Parameters:
    request
    """

    # Get all contacts
    contacts = Contact.objects.filter(user = get_user(request))

    # Get list of jobs and nationalities for filters
    job_list = getJobFilerOptions
    nat_list = getNatFilterOptions

    template_name = 'contacts/webpages/all_contacts.html'

    context = {
        'jobs': job_list,
        'nationality': nat_list,
        'all_contacts': contacts,
        'filtered': False
    }
    return render(request, template_name, context)

def getJobFilerOptions():
    """
    Description: 
    Gets options for job filter drop-down list based on all registered contacts regardless of user

    Parameters:
    request
    """

    jobs = Contact.objects.values_list('job', flat=True).distinct()
    job_list = list(jobs)

    return job_list

def getNatFilterOptions():
    """
    Description: 
    Gets options for nationality filter drop-down list based on all registered contacts regardless of user

    Parameters:
    request
    """

    nationalities = Contact.objects.values_list('nationality', flat=True).distinct()
    nat_list = list(nationalities)

    return nat_list

def filterContacts(request):
    """
    Description: 
    Filters user's contacts by job, nationality, AND sex

    Parameters:
    request
    """

    # Get list of jobs and nationalities for filters
    jobs = Contact.objects.values_list('job', flat=True).distinct()
    job_list = list(jobs)
    nationalities = Contact.objects.values_list('nationality', flat=True).distinct()
    nat_list = list(nationalities)

    if request.method == 'POST': 
        # Query to run filter options
        job_filter = request.POST.get('job')
        nat_filter = request.POST.get('nationality')
        sex_filter = request.POST.get('sex')
        
        # Get filtered list of contacts
        contacts = Contact.objects.filter(job = job_filter, nationality = nat_filter, sex = sex_filter, user = get_user(request))

        # Get filter options
        job_list = getJobFilerOptions
        nat_list = getNatFilterOptions
        
        template_name = 'contacts/webpages/all_contacts.html'

        context = {
            'jobs': job_list,
            'nationality': nat_list,
            'all_contacts': contacts,
            'filtered': True
        }
        return render(request, template_name, context)
    else:
        template_name = 'contacts/forms/filter_contacts.html'

        context = {
            'jobs': job_list,
            'nationality': nat_list
        }
        return render(request, template_name, context)
    
def filterBySex(request):
    """
    Description: 
    Filters user's contacts by sex

    Parameters:
    request
    """

    if request.method == 'POST':
        gender = request.POST['sex']

        contacts = Contact.objects.filter(sex = gender, user = get_user(request)).values()

        # Get list of jobs and nationalities for filters
        job_list = getJobFilerOptions
        nat_list = getNatFilterOptions

        template_name = 'contacts/webpages/all_contacts.html'

        context = {
            'jobs': job_list,
            'nationality': nat_list,
            'all_contacts': contacts,
            'filtered': True
        }
        return render(request, template_name, context)
    
def filterByJob(request):
    """
    Description: 
    Filters user's contacts by job

    Parameters:
    request
    """

    if request.method == 'POST':
        job_name = request.POST['job']

        contacts = Contact.objects.filter(job = job_name, user = get_user(request)).values()

        # Get list of jobs and nationalities for filters
        job_list = getJobFilerOptions
        nat_list = getNatFilterOptions

        template_name = 'contacts/webpages/all_contacts.html'

        context = {
            'jobs': job_list,
            'nationality': nat_list,
            'all_contacts': contacts,
            'filtered': True
        }
        return render(request, template_name, context)
    
def filterByNationality(request):
    """
    Description: 
    Filters user's contacts by nationality

    Parameters:
    request
    """

    if request.method == 'POST':
        nat_name = request.POST['nat']

        contacts = Contact.objects.filter(nationality = nat_name, user = get_user(request)).values()

        # Get list of jobs and nationalities for filters
        job_list = getJobFilerOptions
        nat_list = getNatFilterOptions

        template_name = 'contacts/webpages/all_contacts.html'

        context = {
            'jobs': job_list,
            'nationality': nat_list,
            'all_contacts': contacts,
            'filtered': True
        }
        return render(request, template_name, context)
    
def getActors(request):

    contacts = Contact.objects.filter(job = "Actor").values()

    template_name = 'contacts/webpages/all_contacts.html'

    context = {
        'all_contacts': contacts,
    }
    return render(request, template_name, context)

contacts/templates/contacts/webpages/all_contacts.html
{% extends 'contacts/webpages/base.html' %}

{% block title %} Contacts {% endblock %}

{% block body %}

  <h2>CONTACTS</h2>
  <div class = "container">
    <div class="btn-group" role = "group">
      <!-- Filter Options -->
      <a class="btn btn-outline-secondary" href="{% url 'contacts:filter' %}">Multi-Filter</a>
      <button id="openSexForm" class="btn btn-outline-secondary" onclick="open_button1()">by Sex</button>
      <button id="openJobForm" class="btn btn-outline-secondary" onclick="open_button2()">by Job</button>
      <button id="openNatForm" class="btn btn-outline-secondary" onclick="open_button3()">by Nationality</button>
      {% if filtered %}
        <a class="btn btn-outline-warning" href="{% url 'contacts:all_contacts' %}">Reset Filters</a>
      {% endif %}
    </div>
  </div>
  <br>
  {% if all_contacts %}
    <ul class="list-group list-group-flush">
      {% for contact in all_contacts %}
        <li class="list-group-item">
          <a href="{% url 'contacts:view_contact' contact.id %}"> {{contact.first_name}} {{contact.last_name}} </a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <br>
    <br>
    <p>No contacts</p>
    <br>
    <br>
  {% endif %}

  <!-- Filter by Sex Modal -->
  <div id="sex_modal" class="myModal">

    <!-- Modal content -->
    <div class="myModal-content">
      <span class="modalclose" onclick = "close_button1()">&times;</span>

      <!-- Form -->
      <form action="{% url 'contacts:filter_sex' %}" method="post">
        {% csrf_token %}
        <div>
          <label for="sex">Sex:</label>
          <select name="sex" id="sex">
            <option value="M">Male</option>
            <option value="F">Female</option>
          </select>
        </div>
        <br>
        <br>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" id="submitSexForm" class="btn btn-success">Submit</button>
          </div>
        </div>
      </form>
    </div>

  </div>

  <!-- Filter by Job Modal -->
  <div id="job_modal" class="myModal_2">

    <!-- Modal content -->
    <div class="myModal-content">
      <span class="modalclose" onclick = "close_button2()">&times;</span>

      <!-- Form -->
      <form action="{% url 'contacts:filter_job' %}" method="post">
        {% csrf_token %}
        <div>
          <label for="job">Job:</label>
          <select name="job" id="job">
            {% if jobs %}
              {% for job in jobs %}
                <option value="{{ job }}">{{ job }}</option>
              {% endfor %}
            {% else  %}
            <option value="None">None</option>
            {% endif %}
          </select>
        </div>
        <br>
        <br>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" id="submitJobForm" class="btn btn-success">Submit</button>
          </div>
        </div>
      </form>
    </div>
  </div>

  <!-- Filter by Nationality Modal -->
  <div id="nat_modal" class="myModal_3">

    <!-- Modal content -->
    <div class="myModal-content">
      <span class="modalclose" onclick = "close_button3()">&times;</span>

      <!-- Form -->
      <form action="{% url 'contacts:filter_nationality' %}" method="post">
        {% csrf_token %}
        <div>
          <label for="nat">Nationality:</label>
          <select name="nat" id="nat">
            {% for nat in nationality %}
              <option value="{{ nat }}">{{ nat }}</option>
            {% endfor %}
          </select>
        </div>
        <br>
        <br>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" id="submitNatForm" class="btn btn-success">Submit</button>
          </div>
        </div>
      </form>
    </div>
  </div>

  <br>
  <div class="container">
    <a class="btn btn-primary" href="{% url 'contacts:new_contact' %}">New Contact</a>
  </div>

  <script>
    // Open modals on button click and close on span click
    function open_button1() {
      document.getElementById('sex_modal').style.display = "block";
    }
    function close_button1() {
      document.getElementById('sex_modal').style.display = "none";
    }

    function open_button2() {
      document.getElementById('job_modal').style.display = "block";
    }
    function close_button2() {
      document.getElementById('job_modal').style.display = "none";
    }

    function open_button3() {
      document.getElementById('nat_modal').style.display = "block";
    }
    function close_button3() {
      document.getElementById('nat_modal').style.display = "none";
    }

  </script>
{% endblock %}

contacts/templates/contacts/webpages/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% if user.is_authenticated %}
        {% block title %}{% endblock %}
      {% else %}
        Must Log In
      {% endif%}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/modal.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">WeConnect</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          {% if user.is_authenticated %}
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'user:profile' %}">My Page</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contacts:all_contacts' %}">My Contacts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:logout' %}">Log Out</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search Contact Name" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        {% else %}
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:login' %}">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:register' %}">Sign Up</a>
            </li>
          </ul>
        {% endif %}
        </div>
      </div>
    </nav>
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        {% if user.is_authenticated %}
          {% block body %}
          {% endblock %}
        {% else %}
          <h4> Oops... You aren't logged in yet</h4>
        {% endif %}
    </div>
</body>
</html>

contacts/templates/contacts/webpages/contact_details.html
{% extends 'contacts/webpages/base.html' %}

{% block title %} {{contact.first_name}} {{contact.last_name}} {% endblock %}

{% block body %}

  <ul class="list-group list-group-flush">
    <li class="list-group-item"> Name: {{contact.first_name}} {{contact.last_name}} </li>
    <li class="list-group-item"> Nationality: {{contact.nationality}} </li>
    <li class="list-group-item"> Email: {{contact.email}} </li>
    <li class="list-group-item"> Job: {{contact.job}} </li>
    <li class="list-group-item"> Experience (Years): {{contact.experience}} </li>
    {% comment %} <li class="list-group-item"> Known by: {{user}} </li> {% endcomment %}
  </ul>
  <br>
  {% if contact.sex == 'M' %}
    <h4>About him...</h4>
  {% else %}
    <h4>About her...</h4>
  {% endif %}
  <p> {{contact.bio}} </p>
  <br>
  <div class="container">
    <a href="{% url 'meetings:new_meeting' %}" class="btn btn-primary"> Setup Meeting </a>
    <a href="{% url 'contacts:delete_contact' contact.id %}" class="btn btn-primary"> Delete Contact </a>
    <a href="{% url 'contacts:update_contact' contact.id %}" class="btn btn-primary"> Update Contact </a>
  </div>

 
{% endblock %}